### ISSUE TITLE
Add checks for the command line arguments

### ISSUE THREAD

**Issue by treilly94** [treilly94/wrapper-writer#29]
Check that the command line arguments are valid

**Comment by treilly94** [comment]
[This stackoverflow page](https://stackoverflow.com/questions/19684434/best-way-to-check-function-arguments-in-python) says that it is best to put validation at the entrypoint not in the classes

**Comment by treilly94** [comment]
Added functions to raise argparse.ArgumentTypeErrors

**Comment by KayleighB94** [comment]
#36
